spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5436/demo_db
    username: demouser
    password: demopwd

  flyway:
    enabled: true
    out-of-order: true
    encoding: UTF-8
    schemas: demo_db
    user: demouser
    password: demopwd
