spring:
  jpa:
    generate-ddl: false
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: create-drop
    show-sql: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:app_user_test
    username: demouser
    password: demopwd

  flyway:
    enabled: true
    out-of-order: true
    encoding: UTF-8
    schemas: public
    user: demouser
    password: demopwd

server:
  port: 8082
