spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/world
    username: postgres
    password: docker

  flyway:
    enabled: true
    out-of-order: true
    encoding: UTF-8
    schemas: user_demo
    user: postgres
    password: docker
