spring:
  jpa:
    generate-ddl: false
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: validate
    show-sql: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5437/user_service
    username: demouser
    password: demopwd

  flyway:
    enabled: true
    out-of-order: true
    encoding: UTF-8
    schemas: public
    user: demouser
    password: demopwd


##log config
#logging:
#  level:
#    root: ERROR
#    org:
#      springframework: INFO
#    sql: DEBUG
