spring:
  jpa:
    generate-ddl: false
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: validate
    show-sql: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://host.docker.internal:5437/user_service
    username: demouser
    password: demopwd

  flyway:
    enabled: true
    out-of-order: true
    encoding: UTF-8
    schemas: public
    user: demouser
    password: demopwd

server:
  port: 8083
